default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

  database: crazy4_cats

  # The specified database role being used to connect to PostgreSQL.
  # To create additional roles in PostgreSQL see `$ createuser --help`.
  # When left blank, PostgreSQL will use the default role. This is
  # the same name as the operating system user running Rails.
  username: lopes

  # The password associated with the PostgreSQL role (username).
  password: admin1234

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  
  database: c4c_rails
  username: postgres
  password: Kronos92

  host: localhost
  port: 5432

test:
  <<: *default
  database: c4c_rails_test
  username: postgres
  password: Kronos92
  host: localhost

production:
  <<: *default
  database: c4c_rails_production
  username: postgres
  password: <%= ENV["c4c_rails_DATABASE_PASSWORD"] %>